### ISSUE TITLE
pem.parse ignores PKCS 8 keys

### ISSUE THREAD

**Issue by ldanielburr** [hynek/pem#14]
Files which contain keys in PKCS 8 format, e.g., "BEGIN PRIVATE KEY" are not found by pem.parse.  It appears that pem.parse only looks for PKCS 1 format, e.g., "BEGIN RSA PRIVATE KEY".

**Comment by hynek** [comment]
What should the resulting class be?  Just `pem.Key` or am I missing something?

**Comment by ldanielburr** [comment]
@hynek - In my case the key is still a RSA private key, but I don't see anything in the pem package itself that cares whether the resulting class is pem.Key or pem.RSAPrivateKey, so probably changing the mapping from "RSA PRIVATE KEY": RSAPrivateKey to "PRIVATE KEY": Key would work.

**Comment by hynek** [comment]
Hope this does what you need.

**Comment by ldanielburr** [comment]
@hynek - Yes, that works nicely, thank you.
