### ISSUE TITLE
setup.py should have an `install_requires`

### ISSUE THREAD

**Issue by nickcatal** [hynek/pem#15]
@hynek 

You import the `twisted` library in [`twisted.py`](https://github.com/hynek/pem/blob/36071b8e6d6c73235b21a19fdcb4ee0c4f882ec1/pem/twisted.py#L12) but Twisted is not in `setup.py`

Can you please add Twisted to `install_requires` in `setup.py`?

Thanks!

**Comment by hynek** [comment]
The idea behind pem is that it shouldn’t be usable only with Twisted – it’s just that currently most helpers are Twiste-specific.  That’s why the Twisted APIs moved into a separate module.  I could offer an optional dependency but that would only contain `twisted too`…
