### ISSUE TITLE
Implement __eq__ for PEM objects

### ISSUE THREAD

**Issue by mithrandi** [hynek/pem#22]
Being able to compare these for equality would make my tests simpler, among other things. I guess there's no reason not to implement `__hash__` at the same time?

**Comment by hynek** [comment]
My understanding is that if one implements eq, hash should always be implemented along with it.

**Comment by mithrandi** [comment]
I think it's the other way around: hashable objects must be comparable for equality, but objects comparable for equality do not necessarily need to be hashable. In particular mutable objects should not be hashable, but they can be comparable (eg. `list`).

**Comment by hynek** [comment]
Right.  PEM objects should be both.

**Comment by mithrandi** [comment]
I have a branch mostly done for this, but I'll wait until #24 is merged to PR it since there will be a bunch of stupid conflicts otherwise.
