### ISSUE TITLE
command-line tool for joining, splitting, inspecting pems

### ISSUE THREAD

**Issue by glyph** [hynek/pem#6]
It would be nice to have a command-line tool to perform various simple operations on pems.  Particularly, `pem join somefile.pem otherfile.pem --into=single.pem` to turn `somefile.pem` and `otherfile.pem` into a single file `single.pem` and `pem split somefile.pem` to get `somefile.1.crt.pem`, `somefile.2.key.pem` etc.

With pyOpenSSL installed, this could potentially even give the split files meaningful names.

No less than 3 times in the last 3 weeks, I've been staring at incomprehensible caused by attempting to join and split non-newline-terminated `.pem` files together with `cat` and regexes.  These tasks aren't complex but having reliable ways to do them would be super handy.

**Comment by hynek** [comment]
um is this still something you think is useful – barely 10 years later?

**Comment by glyph** [comment]
@hynek I think that with better tooling (certbot) and standardization (ACME) I spend a lot less time needing to do stuff like this on individual files. But the main thing I wanted to do with this, I am now trying to get a computer to do, instead: https://github.com/twisted/twisted/pull/11861
