### ISSUE TITLE
Pem package is now available on conda-forge

### ISSUE THREAD

**Issue by millsks** [hynek/pem#89]
Howdy.  We are using conda for our package manager and one of our projects that we inherited is using pem.  I created the pem feedstock today and it was promoted to conda-forge.  Would you like me to add you as a maintainer for the feedstock?

- https://anaconda.org/conda-forge/pem
- https://github.com/conda-forge/pem-feedstock

**Comment by hynek** [comment]
Hello, thanks for making pem more widely available and letting me know!

I personally don't have the bandwidth you deal with Conda which also answers you question. :)
